# Generated by Django 3.2 on 2022-08-26 21:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='created_ad',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
