# Generated by Django 3.2 on 2022-09-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='product', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
